name: rentcar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4  # Downgrade para compatibilidad
  flutter_mjpeg: ^2.0.1
  flutter_dotenv: ^6.0.0

  permission_handler: ^11.4.0
  google_maps_flutter: ^2.3.0
  geolocator: ^9.0.2
  http: ^0.13.6
  provider: ^6.1.1
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
